theme: jekyll-theme-minimal
title: Steffen Vering
description: Personal website containing links to my online presence and work highlights.
logo: https://avatars3.githubusercontent.com/u/19303265?s=2000&v=8
